### ISSUE TITLE
what needs to be worked on

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [avramovic/breadly#1]
on what area can i contribute?

**Comment by avramovic** [comment]
Well, for now you could play with Breadly and see if you encounter any issues while using it. Do you know PHP/Laravel?

Also, the [docs](https://github.com/avramovic/breadly/wiki) are pretty thin for now and should be expanded a bit.

**Comment by Abdur-rahmaanJ** [comment]
php yes laravel no but i can learn it !
